modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/BrassGoggledCoders/Workshop/issues"

[[mods]]
    modId="workshop"
    version="${file.jarVersion}"
    displayName="Workshop"
    credits="Divine for the design, Snurly and VeyezX for the art probably"
    authors="Brass Goggled Coders"
    description='''
        This mod adds various lower tier machines to work in tandum with our higher tier machines in other mods to give you a stepping stone type feel
        Spinning Wheel, Sintering Furnace, Seasoning Barrel, Press and Alembic Machines are used to create various types of materials and items!
    '''

[[dependencies.workshop]]
    modId="titanium"
    mandatory=true
    versionRange="[2.3.7,)"
    ordering="NONE"
    side="BOTH"
